apiVersion: v1
kind: Secret
metadata:
  name: codesnippet-secrets
  namespace: codesnippet-manager
type: Opaque
data:
  # Base64 编码的值，需要在部署时替换
  DB_CONNECTION_STRING: # echo -n "your-connection-string" | base64
  JWT_SECRET_KEY: # echo -n "your-jwt-secret" | base64
  MYSQL_ROOT_PASSWORD: # echo -n "your-mysql-root-password" | base64
  MYSQL_USER: # echo -n "your-mysql-user" | base64
  MYSQL_PASSWORD: # echo -n "your-mysql-password" | base64